services:
  - type: web
    name: rag-battle-arena-api
    runtime: docker
    plan: free
    repo: https://github.com/mrisahoo1/RAG-Battle-Arena
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: ENABLE_DEMO_MODE
        value: "true"
